Jcn 465 manage short links
janis-commerce/handlebars pull request #10
Opened 2024-01-15 18:13 UTC by moruezabal

**Descripción:**
Nuevo helper `shortLink`  que devuelve los links con un wrapper estilo `#SHORTLINK[linkLargo]`

Ejemplos de uso:

```
{{{shortLink url}}}

{{{shortLink 'https://cdn.microsite.janisdev.in/tracking?client=fizzmodarg&trackingId=' shipping.displayId}}}
```

Nuevo método `postCompile` para generar y reemplazar los links largos con wrapper a links cortos

Este método recibe un parámetro para saber si generar o no los links cortos (para evitar generar links cortos al editar templates)

En caso de que el parámetro sea true, Invoke al MS y reemplazo de los links. Si la generación falla, devuelve el link largo

En caso de que sea false, no genera links y solo elimina el wrapper, devolviendo el link largo

**Descripción de la solución:**

- Se añadió el helper `shortLink `

Este intenta validar si el parámetro ingresado es una URL válida, utilizando el constructor de URL. Si falla, devuelve `Invalid URL`, si tiene éxito, devuelve `#SHORTLINK[link]`

- Se añadió el constructor postCompile
 Se añadió un nuevo constructor, que en el process manipula el template pasado por parámetro para reemplazar todas las ocurrencias `#SHORTLINK[link]` por links generados desde MS Link
Si la generación falla devuelve el link original, sin el wrapper.
Finalmente reemplaza según el link todas las coincidencias en el texto por el link resultante

2024-01-17 16:25 UTC, Alejandro-Gonzalez requested changes
Te deje unos ajustes!

2024-01-17 16:25 UTC, Alejandro-Gonzalez commented on lib/controllers/post-compile.js
> +		this.shortLink = settings.hasOwnProperty('shortLink') ? settings.shortLink : true;
@moruezabal acá podrías hacer y te ahorras el default del settings

```js
this.shortLink = setting?.shortLink ?? true;
```

2024-01-17 16:25 UTC, Alejandro-Gonzalez commented on lib/controllers/post-compile.js
> +			const exp = new RegExp('#SHORTLINK\\[' + escapeRegExp(longLink) + '\\]', 'g');
@moruezabal como ves mejor asi
```js
const exp = new RegExp(`#SHORTLINK\\[${escapeRegExp(longLink)}\\]`, 'g');
```

2024-01-17 16:25 UTC, Alejandro-Gonzalez commented on lib/controllers/post-compile.js
> +		const { payload: { shortUrl } } = await Invoker.serviceSafeCall('link', 'CreateLink', { target: originalLink });
@moruezabal aca tendría cuidado con el `{ payload: { shortUrl } }`, lo usaria asi
`payload?.shortUrl`, por si no te llega el payload
Supongo que si tenemos algún tipo de error de lambda no hacemos nada no? Seguimos para adelante nomas?

2024-01-18 12:56 UTC, moruezabal commented on lib/controllers/post-compile.js
> +		const { payload: { shortUrl } } = await Invoker.serviceSafeCall('link', 'CreateLink', { target: originalLink });
Claro, seguimos para adelante, por eso utilicé el safe.
La idea es que cualquier tipo de error que haya el helper devuelva `Invalid URL`

2024-01-18 14:04 UTC, Alejandro-Gonzalez approved these changes

2024-01-19 18:06 UTC, argenis1763 requested changes

2024-01-19 18:06 UTC, argenis1763 commented on lib/controllers/post-compile.js
> +		if(!this.shortLink) {
Me parece que puedes mejorar el código y tener el mismo resultado haciendo algo así:

```
async getShortlink(wrappedlink) {

    const originalLink = wrappedlink.slice(11, -1); // Extract link from '#SHORTLINK[link]'

    const response = this.shortLink && await Invoker.serviceSafeCall('link', 'CreateLink', { target: originalLink });

    this.shortLinksByLink[originalLink] = response?.payload?.shortUrl || originalLink;
}
```

2024-01-19 18:06 UTC, argenis1763 commented on lib/helpers.js
> + *                    If the URL is invalid, returns 'Invalid URL'.
Falta agregar la propiedad `@example` para detallar casos de uso, toma como ejemplo los ya existentes

2024-01-19 18:06 UTC, argenis1763 commented on lib/helpers.js
> +		return 'Invalid URL';
Mmm me parece que en vez de devolver este mensaje, devolvería un string vació `return '';`

2024-01-19 21:26 UTC, moruezabal commented on lib/helpers.js
> +		return 'Invalid URL';
Lo había pensado como alternativa, pero entendía que un string te daba más info sobre que el helper estaba actuando

2024-01-20 16:19 UTC, argenis1763 commented on lib/helpers.js
> + * const invalidURL = 'not_a_valid_url';
No me refería a detallar un ejemplo de código en javascript si no de sintaxis handlebars de casos de uso, por eso te decía que vieras como eran los ejemplos de los otros métodos.

```
@example {{shortlink url}} => "#SHORTLINK[https://example.com]"
```
De un ejemplo asi hablaba, ajustemos esto y creo que con eso estamos.

2024-01-22 12:38 UTC, moruezabal commented on lib/helpers.js
> + * const invalidURL = 'not_a_valid_url';
Bien, ahí te entendí que ejemplos tenía que ver 👌🏻 
Arreglé el nombre de la variable del helper también

2024-01-22 13:52 UTC, argenis1763 commented on tests/handlebars-helpers-test.js
> +		const otherTemplate = '<html><body><h1>{{shortLink "https://janis.im"}}</h1></body></html>';
Agreguemos la constante `otherTemplate` y `otherTemplateCompiled` directamente en el test que corresponde ya que no tiene sentido tenerlas declaradas afuera si solo se usan una vez

2024-01-22 13:55 UTC, argenis1763 approved these changes
@moruezabal te apruebo el PR pero te deje un ultimo corrección que debes aplicar

2024-01-23 17:23 UTC, merged