Jcn 340 add functionality of qr and code128
janis-commerce/handlebars pull request #4
Opened 2021-11-03 18:52 UTC by MarianoFndz

### Link al ticket
https://fizzmod.atlassian.net/browse/JCN-338

### Link a la subtarea
https://fizzmod.atlassian.net/browse/JCN-340

### Descripción del requerimiento
* Se deberá agregar un método preCompile en donde:

   * En caso de que exista una key que comience con qr_ se deberá formatear como un código QR mediante la librería qrcode

      * Se deberá usar el método toDataURL de la misma

     * No se deberá settear ninguna de las opciones extras de la misma

     * Se deberá soportar la posibilidad de múltiples QR distintos

   * En caso de que exista una key que comience con barcode128_ se deberá formatear como un barcode128 usando la librería bwip-js

     * Se deberá usar el método toBuffer con las siguientes configs por default

        * bcid: 'code128'

        * text: barcode128Data

        * scale: 3

        * height: 10

        * includetext: true

        * textxaling: 'center'

     * Luego se deberá usar el método toString('base64') para armar la imágenes

  * Se deberá documentar como usar dichas funcionalidades, tanto el qr_ como el barcode128_

### Descripción de la solución
Se realizo el requerimiento

2021-11-05 14:28 UTC, argenis1763 commented on lib/controllers/pre-compile-controller.js
> +	constructor(data) {
Para este caso eliminaría el método `constructor` y enviaría directamente la data como parámetro en el método `process`

2021-11-05 14:45 UTC, argenis1763 commented on lib/controllers/pre-compile-controller.js
> +		return this.format(this.data);
- Que pasa si `data` llega vacío? 
- Que tipo de dato estas esperando en `data`?

Te sugiero que si esta soportando un `object` que lo validez.
Por ultimo, la variable `data` con ese nombre no da mucho contexto de lo que estaría almacenando, podrías cambiarlo por algo mejor.

2021-11-05 15:03 UTC, argenis1763 commented on lib/controllers/pre-compile-controller.js
> +		await this.formatKeysWithoutCodeFormats(keysWithoutCodeFormat, data, dataFormatted);
No podría ser un `Promise.all`?

```
Promise.all([
    this.formatKeysWithoutCodeFormats(keysWithoutCodeFormat, data, dataFormatted),
    this.formatKeysWithCodeFormats(keysWithCodeFormat, data, dataFormatted)
]);
```
O por algún motivo hay que esperar que se ejecute primero?

2021-11-05 15:05 UTC, argenis1763 commented on lib/controllers/pre-compile-controller.js
> +		const dataFormatted = {};
Igual que `data` utilicemos un nombre mas descriptivo.

2021-11-05 15:22 UTC, argenis1763 commented on lib/controllers/pre-compile-controller.js
> +			if(!key || typeof data[key] !== 'object' || !data[key]) {
mmm en que caso `key` o `data[key]` no existirían? Entiendo que son campos que se extraen del objeto `data` previamente. Me parece que alcanzaría con `if(typeof data[key] !== 'object')` no?

2021-11-05 15:38 UTC, argenis1763 commented on lib/handlebars.js
> +	const preCompileController = new HTMLPreCompileController(data);
Cambiaría por algo así:
```
const preCompileController = new HTMLPreCompileController();
return preCompileController.process(templateValues);
```

2021-11-05 15:41 UTC, argenis1763 commented on lib/handlebars.js
> +const HTMLPreCompileController = require('./controllers/pre-compile-controller');
Me parece que la palabra `controller` podría estar sobrando en el nombre del archivo dejaría `pre-compile`, que te parece?

2021-11-05 15:45 UTC, argenis1763 commented
Te hace falta modificar el **README** del package, recuerda que estas agregando una nueva funcionalidad y es importante que quede bien explicada para el resto de los usuarios que lleguen a utilizar el :package:

2021-11-05 15:48 UTC, argenis1763 commented on tests/handlebars-pre-compile-test.js
> +
Debería agregar algún test para el escenario donde recibas un estructura invalida.

2021-11-05 15:51 UTC, argenis1763 requested changes
Te deje algunos comentarios mínimos, importante modificar el **README**.

2021-11-05 20:59 UTC, gastonpereyra commented on lib/controllers/pre-compile-controller.js
> +		return this.format(this.data);
En JDG, lo que aca se llamó `data` es siempre un `object` porque se controla antes (struct / validate de api).

Esto es porque son los valores para cambiar en el template usando Handlebars.

Por lo que si, la idea de Argenis de validarlo esta bien.

Por otro lado, también apoyo la idea de eliminar el constructor, en este contexto es innecesario. y es más eligiria si el método se llama `process` o `format` porque al final es un pasamanos que no le veo mucho sentido.

> En JDG originalmente esta clase tenia más funciones por eso habia un `format` separado del método central

2021-11-05 21:02 UTC, gastonpereyra commented on lib/controllers/pre-compile-controller.js
> +			if(!key || typeof data[key] !== 'object' || !data[key]) {
No. Yo pensaba lo mismo hasta que lo empezamo a usar, y aparecieron cosas como 

```json
{
 "qr_fizzmod": "https://app.janis.in",
 "age": null
}
```
Y rompia todo..

Por lo que `!data[key]`, es una validación necesaria.

2021-11-15 13:02 UTC, argenis1763 requested changes
Comentarios mínimos

2021-11-15 13:02 UTC, argenis1763 commented on docs/preCompile.md
> +	barcode128_ean: '123123'
Pareciera que tuvieras un espacio demás puede ser?

2021-11-15 13:02 UTC, argenis1763 commented on docs/preCompile.md
> +	barcode128_ean: 'data:image/png;base64,ivBoQR01W'
Acá igual pareciera que tuvieras un espacio demás

2021-11-15 13:02 UTC, argenis1763 commented on lib/controllers/pre-compile.js
> +		if(typeof templateValues !== 'object' || Array.isArray(templateValues))
`null` es considerado `object`

2021-11-15 13:32 UTC, argenis1763 approved these changes
Aprobado!

2021-11-15 20:58 UTC, merged